export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const LOAD_INVENTORY = 'LOAD_INVENTORY';
export const LOAD_INVENTORY_IN_BACKGROUND = 'LOAD_INVENTORY_IN_BACKGROUND';
export const RESTART_INVENTORY = 'RESTART_INVENTORY';
export const LOAD_PAGE_INVENTORY = 'LOAD_PAGE_INVENTORY';
export const REQUEST_INVENTORY = 'REQUEST_INVENTORY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const EDIT_BOX = 'EDIT_BOX';
export const REQUEST_EDIT_BOX = 'REQUEST_EDIT_BOX';
export const CUSTOM_BOX_OPEN_MODAL = 'CUSTOM_BOX_OPEN_MODAL';
export const REQUEST_ADD_TO_CART = 'REQUEST_ADD_TO_CART ';
export const LIST_SHOPPING_CART = 'LIST_SHOPPING_CART';
export const CHECK_OPEN_BOX = 'CHECK_OPEN_BOX';
export const REQUEST_CHECK_OPEN_BOX = 'REQUEST_CHECK_OPEN_BOX';
export const SET_FAVORITE = 'SET_FAVORITE';
export const REQUEST_SET_FAVORITE = 'REQUEST_SET_FAVORITE';
export const INIT_FINISH_ORDER = 'INIT_FINISH_ORDER';

export const ADD_FILTER = 'ADD_FILTER';
export const REQUEST_PAGE = 'REQUEST_PAGE';
export const TOGGLE_SINGLE_FILTER = 'TOGGLE_SINGLE_FILTER';
export const TOGGLE_SORT_FILTER = 'TOGGLE_SORT_FILTER';
export const TOGGLE_COMPOSED_FILTER = 'TOGGLE_COMPOSED_FILTER';
export const ADD_COMPOSED_FILTER = 'ADD_COMPOSED_FILTER';
export const REMOVE_COMPOSED_FILTER = 'REMOVE_COMPOSED_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const ADD_SEARCH_FILTER = 'ADD_SEARCH_FILTER';

export const CHANGE_CUSTOMER_ADDRESS = 'CHANGE_CUSTOMER_ADDRESS';
export const CHANGE_ALL_CUSTOMER_INFO = 'CHANGE_ALL_CUSTOMER_INFO';
export const ADD_CUSTOM_BOX = 'ADD_CUSTOM_BOX';
export const CANCEL_CUSTOM_BOX = 'CANCEL_CUSTOM_BOX';
export const CLOSE_CUSTOM_BOX = 'CLOSE_CUSTOM_BOX';
export const REMOVE_FROM_CUSTOM_BOX = 'REMOVE_FROM_CUSTOM_BOX';
export const REQUEST_REMOVE_FROM_CUSTOM_BOX = 'REQUEST_REMOVE_FROM_CUSTOM_BOX';
export const KEEP_EDITING_CUSTOM_BOX = 'KEEP_EDITING_CUSTOM_BOX';
export const FINISH_SHOPPING_LIST = 'FINISH_SHOPPING_LIST';

export const LIST_SCHEDULE = 'LIST_SCHEDULE';
export const SHOW_SHOPPING_CART = 'SHOW_SHOPPING_CART';
export const FINISH_ORDER = 'FINISH_ORDER';
export const REQUEST_CHECKOUT = 'REQUEST_CHECKOUT';
export const REQUEST_ADDING_TO_CUSTOM_BOX = 'REQUEST_ADDING_TO_CUSTOM_BOX';
export const LIST_CARDS = 'LIST_CARDS';
export const CHANGE_DEFAULT_CARD = 'CHANGE_DEFAULT_CARD';
export const CHANGE_SELECTED_CARD = 'CHANGE_SELECTED_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const ACTIVE_SINGLE_FILTER = 'ACTIVE_SINGLE_FILTER';
export const CLEAN_CONDITIONS = 'CLEAN_CONDITIONS';
export const REQUEST_DELETE_BOX = 'REQUEST_DELETE_BOX';
export const DELETE_BOX = 'DELETE_BOX';
export const REQUEST_CANCEL_SL_ITEM = 'REQUEST_CANCEL_SL_ITEM';
export const CANCEL_SL_ITEM = 'CANCEL_SL_ITEM';

export const GET_ORDER_TO_SHIP = 'GET_ORDER_TO_SHIP';
export const VALIDATE_VOUCHER = 'VALIDATE_VOUCHER';
export const CANCEL_VOUCHER = 'CANCEL_VOUCHER';
export const REQUEST_VALIDATE_VOUCHER = 'REQUEST_VALIDATE_VOUCHER';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CLEAN_MODAL = 'CLEAN_MODAL';

export const GET_HOLIDAYS = 'GET_HOLIDAYS';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const HOME_LOADING = 'HOME_LOADING';
export const SET_LAST_DATE = 'SET_LAST_DATE';
export const TOGGLE_SHOW = 'TOGGLE_SHOW';
export const SHOW_CUSTOM_BOX = 'SHOW_CUSTOM_BOX';

export const CLEAN_UI_STATE = 'CLEAN_UI_STATE';
export const INIT_SEND_REFERRAL = 'INIT_SEND_REFERRAL';
export const SEND_REFERRAL = 'SEND_REFERRAL';
export const ERROR_REFERRAL = 'ERROR_REFERRAL';
export const LOAD_REFERRALS = 'LOAD_REFERRALS';
export const INIT_LOAD_REFERRALS = 'INIT_LOAD_REFERRALS';
export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP = 'SIGNUP';
export const SIGNUPOBJECT = 'SIGNUPOBJECT';
export const LOGIN_USER = 'LOGIN_USER';

export const CHANGE_INVALID_TOKEN = 'CHANGE_INVALID_TOKEN';
